version: '3'
services:
  # app:
  #   image: python:3.9-slim
  #   command: sh -c "pip install -r requirements.txt && python app.py"
  #   # build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./app:/app
  #   working_dir: /app

  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  
    working_dir: /app

  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-storage:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: root

  
  promtail:
    image: grafana/promtail
    volumes:
      - ./configs/promtail-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
    command:
      - '-config.file=/etc/promtail/config.yml'
    

volumes:
  grafana-storage:
  loki-storage: