global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['app:5000'] 
        labels:
          service: 'flask-app'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']